### ISSUE TITLE
Error GLCM PNG file

### ISSUE THREAD

**Issue by lrocax** [joelcarlson/radiomics#8]
Dear Mr. Carlson,

I am trying to use your radiomics package and while I read a small PNG file via this small script I get this an error:

> im <- readPNG("D:/U2.png")
> im_glcm <- glcm(im)
> Error in discretizeImage(data, n_grey = n_grey, ...) :
>   Object of class array.  is.matrix(object) must evaluate TRUE.

I will appreciate if you can explain me why and how can I solve it?

Thanks a lot,
Lluis

![u2](https://cloud.githubusercontent.com/assets/5468677/14899115/4641b288-0d93-11e6-827b-9cc79d26cc79.png)

**Comment by joelcarlson** [comment]
Hi Lluis, 

Did you download the package from CRAN, or from github? I haven't released a version to CRAN in some time. 

PNG files should read into R as matrices though, so this error seems a little strange.

Try downloading from github, if that doesn't work then maybe send me the png and I can try to debug!

Best,
Joel

**Comment by lrocax** [comment]
I used the install_github("joelcarlson/radiomics", ref="develop") but the error still remain. I have attached the PNG in the original message. I presume it is something with the PNG file.

**Comment by joelcarlson** [comment]
I looked into the issue - the problem is that png files read into R into a 3 dimensional array (which I suppose should have been obvious, given the error message). The radiomics package expects the data to be in a 2D matrix. In your case, all three dimensions of the array are identical so you can use:

`
glcm_im = glcm(im[,,1])
`

However, a further issue is that the expected pixel values of the image are value between 1 and 255. You should therefore use:

`
glcm_im = glcm(255*im[,,1])
`

Sorry about the issue! Let me know if you need anything else.

**Comment by lrocax** [comment]
Thanks a lot, I presume I have to do the same with glrlm and glszm.
e.g.:

> ```
>   im_glrlm <- glrlm(255*im[,,1])
>   im_glszm <- glszm(255*im[,,1])
> ```

**Comment by joelcarlson** [comment]
Correct!
